title: Yağmur Uçkunkaya # your name (or website title) here
logo: "/images/Screenshot 2021-02-04 at 14.39.37.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Presenting the results of speech and singing synthesis through transfer learning and perturbation using Tacotron-2.  
theme: jekyll-theme-minimal
